settings:
  title: 'Status Page'
  url: 'https://watcher.mico.run' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: h5.sxj5888.com  # unique identifier
    name: YLT h5
    description: 'h5.sxj5888.com.' # default=empty
    url: 'https://h5.sxj5888.com/index.html' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    linkable: true # allows the title to be a link, default=true

  - id: h5d.sxj5888.com
    name: YLT h5d
    description: 'h5d.sxj5888.com'
    url: 'https://h5d.sxj5888.com/manifest.json'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: mico-run
    name: mico-run-website
    url: 'https://www.mico.run/'
    method: GET
    expectStatus: 200
